### ISSUE TITLE
question

### ISSUE THREAD

**Issue by anotherfinemess84** [Wo1fie/anti-gg#1]
could this work on the 1.6 variant, the gg process is randomised.

**Comment by Wo1fie** [comment]
Sorry for the late response.  This would have to be done via code.  You should be able to find the active gg process by looking at how it's randomized, its location, or worst case by checking processes for a dll that only gg loads.

This project is really just an archive/starting point.  I have not been able to test it on any recent build of gg.  The last time this was actively used was over 10 years ago.  I built this in high school.
